import {useEffect,useRef,useState} from 'react';
import {Boxes,Truck,FileText,Database,BookOpen,Calculator,ArrowDownToLine,Search,X,ArrowUpRight} from 'lucide-react';
import {api,overridesFor} from './api.js';
import ForecastPeriod from './forecast-period.jsx';
import DataSources from './data-sources.jsx';
import './purchasing-prototype.css';
import './elektro.css';

const navigation=[['planning','Пополнение склада','Расчёт и проверка потребности',Boxes],['orders','Заказы поставщикам','Версии, утверждение и экспорт',Truck],['sources','Источники данных','Импортированные товары и документы',Database],['method','Логика расчёта','Факторы спроса и ограничения',BookOpen]];
const show=value=>value===null||value===undefined?'—':String(value).replace(/\.0+$/, '').replace(/(\.\d{6})\d+$/, '$1…');
const nullable=value=>value===''?null:value;
const addDays=(day,n)=>{const date=new Date(day+'T00:00:00Z');date.setUTCDate(date.getUTCDate()+n);return date.toISOString().slice(0,10);};
const today=()=>{const now=new Date();return `${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}-${String(now.getDate()).padStart(2,'0')}`;};
function Field({label,value,onChange,...props}){return <label>{label}<input value={value??''} onChange={e=>onChange(e.target.value)} {...props}/></label>;}

export default function ConnectedWorkspace(){
  const [view,setView]=useState('planning'),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const running=useRef(false),dialog=useRef(null);
  const [input,setInput]=useState(null),[computed,setComputed]=useState(null),[result,setResult]=useState(null);
  const [scenario,setScenario]=useState(null),[savedList,setSavedList]=useState([]),[name,setName]=useState('');
  const [edits,setEdits]=useState({}),[notes,setNotes]=useState({}),[query,setQuery]=useState(''),[supplier,setSupplier]=useState('');
  const [warehouses,setWarehouses]=useState([]),[cases,setCases]=useState([]),[books,setBooks]=useState([]),[usage,setUsage]=useState([]);
  const [catalog,setCatalog]=useState({items:[],total:0,page:1}),[search,setSearch]=useState(''),[selected,setSelected]=useState({});
  const [source,setSource]=useState({planning_date:today(),warehouse:'',history_start:addDays(today(),-56),history_end:addDays(today(),-1),normalizer_version:'',workbook_ids:[]});
  const [detail,setDetail]=useState(null),[editor,setEditor]=useState(null),[reason,setReason]=useState('');
  const [confirm,setConfirm]=useState(false),[actor,setActor]=useState(''),[ack,setAck]=useState(false);
  useEffect(()=>{if(detail||editor||confirm)dialog.current?.showModal();else dialog.current?.close();},[detail,editor,confirm]);
  async function run(work){if(running.current)return;running.current=true;setBusy(true);setError('');try{await work();}catch(e){setError(e.message);}finally{running.current=false;setBusy(false);}}
  async function refreshSaved(){setSavedList((await api('/scenarios')).items);}
  async function loadCatalog(page=1){
    const data=await api(`/tables/catalog?${new URLSearchParams({page,page_size:20,q:search})}`);
    const items=await Promise.all(data.items.map(async item=>{const attrs=await api(`/tables/products?${new URLSearchParams({product_id:item.id,page_size:200})}`);const names=[...new Set(attrs.items.map(a=>a.name).filter(Boolean))];return {...item,name:names[0]||item.sku,nameConflict:names.length>1};}));
    setCatalog({...data,items});
  }
  async function refreshImported(){
    const [places,files]=await Promise.all([api('/tables/warehouses?page_size=200'),api('/tables/workbooks?page_size=200')]);
    setWarehouses(places.items);setBooks(files.items);await loadCatalog();
  }
  useEffect(()=>{run(async()=>{const [places,demos,files]=await Promise.all([api('/tables/warehouses?page_size=200'),api('/planning/demo-cases'),api('/tables/workbooks?page_size=200')]);setWarehouses(places.items);setCases(demos);setBooks(files.items);if(places.items.length===1)setSource(s=>({...s,warehouse:places.items[0].name}));await refreshSaved();});},[]);
  async function calculate(next){const response=await api('/planning/calculate',next);setInput(structuredClone(next));setComputed(structuredClone(next));setResult(response);setScenario(null);setEdits({});setNotes({});setSupplier('');setView('planning');setName(`Закупка ${next.planning_date}`);}
  async function loadSaved(id){const saved=await api(`/scenarios/${id}`);setScenario(saved);setName(saved.name);setInput(structuredClone(saved.input));setComputed(structuredClone(saved.input));setResult(saved.result);setEdits(Object.fromEntries(saved.overrides.map(o=>[o.row_id,o.quantity])));setNotes(Object.fromEntries(saved.overrides.map(o=>[o.row_id,o.reason])));setUsage([]);setSupplier('');setView('orders');}
  const rows=result?.rows||[],dirty=JSON.stringify(input)!==JSON.stringify(computed);
  let overrides=[],invalid='';try{overrides=overridesFor(rows,edits,notes);}catch(e){invalid=e.message;}
  const changed=!scenario||JSON.stringify(overrides)!==JSON.stringify(scenario.overrides)||name!==scenario.name;
  const approved=!!scenario&&!dirty&&!changed&&!invalid&&scenario.approved_revision===scenario.revision;
  const blocked=rows.some(row=>row.status==='needs_input'),canSave=!!result&&!dirty&&!invalid&&!!name.trim(),canApprove=canSave&&!blocked;
  const suppliers=[...new Set(rows.map(row=>row.supplier))],ordered=rows.filter(row=>Number(edits[row.row_id]||row.recommended_quantity)>0);
  const visible=rows.filter(row=>(!supplier||row.supplier===supplier)&&`${row.sku} ${row.name}`.toLocaleLowerCase('ru').includes(query.toLocaleLowerCase('ru')));
  const resultRow=rows.find(row=>row.row_id===detail),sourceRow=input?.rows.find(row=>row.row_id===detail);
  async function save(){
    if(!canSave)throw new Error(invalid||'Пересчитайте входы и укажите название.');
    let saved=scenario;if(!saved)saved=await api('/scenarios',{name,input:computed});
    if(scenario||overrides.length)saved=await api(`/scenarios/${saved.id}`,{expected_revision:saved.revision,name,input:computed,overrides},'PUT');
    setScenario(saved);setName(saved.name);await refreshSaved();return saved;
  }
  async function approve(){const saved=changed?await save():scenario;const updated=await api(`/scenarios/${saved.id}/approve`,{expected_revision:saved.revision,approved_by:actor.trim(),acknowledge_scenario:true});setScenario(updated);setConfirm(false);setView('orders');await refreshSaved();}
  const close=()=>{if(!busy){setDetail(null);setEditor(null);setConfirm(false);}};
  const update=(key,value)=>setInput(previous=>({...previous,[key]:value}));
  const openEditor=row=>{setDetail(null);setEditor(structuredClone(row));setReason('');};
  const navigate=id=>{setView(id);if(id==='sources')run(()=>loadCatalog());if(id==='orders')run(refreshSaved);};
  return <div className="pp2 ek">
    <aside className="pp2-sidebar"><div className="pp2-brand"><span>ЭК</span><div><strong>ЭЛЕКТРОКОМПЛЕКТ</strong><small>КОНТУР ЗАКУПОК</small></div></div><div className="ek-workspace-label">РАБОЧЕЕ МЕСТО ЗАКУПЩИКА</div><nav aria-label="Основное меню">{navigation.map(([id,label,desc,Icon])=><button disabled={busy} key={id} className={id===view?'is-active':''} onClick={()=>navigate(id)}><span className="pp2-nav-icon"><Icon/></span><span className="pp2-nav-copy"><b>{label}</b><small>{desc}</small></span></button>)}</nav><div className="pp2-sidebar-footer"><div className="pp2-source"><span/><div><strong>Локальная база данных</strong><small>Сценарии · без отправки</small></div></div></div></aside>
    <main className="pp2-main" aria-busy={busy}>
      <div className="ek-topline"><span>Электрокомплект / Рабочее пространство</span><span className="ek-demo">СЦЕНАРИЙ · {computed?.planning_date||'выберите данные'}</span></div><nav className="ek-mobile-nav" aria-label="Разделы">{navigation.map(([id,label])=><button disabled={busy} key={id} onClick={()=>navigate(id)} aria-current={view===id?'page':undefined}>{label}</button>)}</nav>
      <header className="pp2-heading ek-heading"><div><p>ПЛАНИРОВАНИЕ ЗАКУПОК</p><h1>{navigation.find(n=>n[0]===view)[1]}</h1><div className="ek-subtitle">От истории продаж — к обоснованному заказу поставщику.</div></div><span className="ek-person">МЗ <small>Менеджер закупок</small></span></header>
      <div className="ek-notice">Расчёт выполняется на сервере. Бизнес-политики требуют подтверждения EKT; неизвестные значения не заменяются нулями. Заказы автоматически не отправляются.</div>{error&&<div role="alert" className="ek-warning">{error}</div>}{busy&&<p role="status">Обрабатываем запрос…</p>}
      {view==='sources'&&<DataSources onImported={()=>run(refreshImported)}/>}
      {(view==='planning'||view==='orders')&&<>
        <section className="ek-card ek-controls"><button className="ek-secondary" disabled={busy} onClick={()=>navigate('sources')}><Database size={17}/>Выбрать товары</button><label>Синтетический пример<select disabled={busy} value="" onChange={e=>{const demo=cases.find(item=>item.id===e.target.value);if(demo)run(async()=>{setUsage([]);await calculate(demo.input);});}}><option value="">Выберите явно учебный пример</option>{cases.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label>
          {input&&<><ForecastPeriod input={input} onChange={setInput} disabled={busy}/><button className="ek-primary" disabled={busy} onClick={()=>run(()=>calculate({...input,forecast_method:'auto'}))}><Calculator size={17}/>Рассчитать потребность</button>
          {[['lead_time_days','Срок новой поставки, дней',0],['review_days','Интервал пересмотра, дней',1]].map(([key,label,min])=><Field key={key} label={label} type="number" min={min} max="365" value={input[key]} onChange={value=>update(key,value===''?null:Number(value))}/>)}
          {[['buffer_days','Страховой запас, дней'],['growth_pct','Дополнительный рост, %']].map(([key,label])=><Field key={key} label={label} inputMode="decimal" value={input[key]} onChange={value=>update(key,value)}/>)}
          <details className="ek-factors"><summary>Факторы расчёта и сезонность</summary><div>{[['exclude_bulk','Исключать разовые документные всплески'],['compensate_stockouts','Восстанавливать спрос по известным датам stockout']].map(([key,label])=><label key={key}><input type="checkbox" checked={input[key]} onChange={e=>update(key,e.target.checked)}/>{label}</label>)}</div><p>Месячные коэффициенты — явные допущения. Индивидуальные параметры товара имеют приоритет.</p><div className="ek-source-grid">{Array.from({length:12},(_,i)=>String(i+1)).map(month=><Field key={month} label={`Месяц ${month}, коэффициент`} value={input.seasonality[month]??'1'} onChange={value=>update('seasonality',{...input.seasonality,[month]:value})}/>)}</div></details>
          <p className="ek-factors">{input.forecast_end?`Свой период: ${input.planning_date} — ${input.forecast_end}, обе даты включены. Срок поставки не прибавляется повторно.`:'Без своих дат горизонт каждой позиции = срок поставки + интервал пересмотра (до 730 дней).'} Дата расчёта не подтверждает свежесть остатков.</p></>}
        </section>
        {view==='orders'&&<section className="ek-card ek-info"><h2>Сохранённые сценарии</h2><button className="ek-secondary" disabled={busy} onClick={()=>run(refreshSaved)}>Обновить список</button>{savedList.map(item=><p key={item.id}><button className="ek-secondary" disabled={busy} onClick={()=>run(()=>loadSaved(item.id))}>{item.name} · версия {item.revision} · {item.approved_revision===item.revision?'Утверждён':'Черновик'}</button></p>)}{!savedList.length&&<p>Пока нет сохранённых сценариев.</p>}</section>}
        {dirty&&<p className="ek-warning" role="status">Параметры изменены. Пересчитайте потребность перед сохранением и утверждением.</p>}
        {!!result&&<section className="ek-forecast-method" aria-label="Методы прогноза"><strong>Метод по каждому товару</strong><p>{[...new Set(rows.map(row=>row.forecast_method))].map(method=>({weekly_ewma:'Взвешенный спрос за 8 недель',history_mean:'Среднее по истории',manual_daily_demand:'Явно заданный дневной спрос'}[method]||'Среднее / явный спрос по прежнему расчёту')).join(' · ')}</p><small>После пересчёта: 56 дней истории → взвешенный спрос; короткая история или компенсация отсутствия → среднее. Явный спрос товара сохраняет приоритет. LightGBM пока не подключён.</small></section>}
        {!result?<section className="ek-card ek-empty">Выберите импортированные товары или синтетический пример. При ошибке сервера вымышленные данные не подставляются.</section>:<>
          <section className="ek-metrics"><article><span>К пополнению</span><strong>{ordered.length}<small> / {rows.length} SKU</small></strong><p>{suppliers.length} поставщика</p></article><article className="ek-risk"><span>Дефицит до прихода</span><strong>{rows.filter(r=>Number(r.maximum_prearrival_shortfall)>0).length}<small> SKU</small></strong><p>Обычный заказ не устраняет ранний дефицит</p></article><article><span>Требуют уточнения</span><strong>{rows.filter(r=>r.status==='needs_input').length}<small> SKU</small></strong><p>Нет количества для утверждения</p></article><article><span>Исключены всплески</span><strong>{rows.filter(r=>Number(r.excluded_bulk_quantity)>0).length}<small> SKU</small></strong><p>Статистические кандидаты</p></article></section>
          <div className="ek-toolbar"><div className="ek-tabs"><button className={view==='planning'?'active':''} onClick={()=>setView('planning')}>Рекомендации</button><button className={view==='orders'?'active':''} onClick={()=>navigate('orders')}>Заказы по поставщикам</button></div><div className="ek-search"><Search size={16}/><input aria-label="Поиск SKU или товара" value={query} onChange={e=>setQuery(e.target.value)}/></div><select aria-label="Фильтр поставщика" value={supplier} onChange={e=>setSupplier(e.target.value)}><option value="">Все поставщики</option>{suppliers.map(s=><option key={s}>{s}</option>)}</select></div>
          <div className="ek-results"><div className="ek-groups">{suppliers.filter(s=>visible.some(r=>r.supplier===s)).map(s=><section className="ek-card ek-supplier" key={s}><header><div><Truck size={19}/><div><h2>{s}</h2><p>Сроки и единицы — по каждой позиции</p></div></div></header><div className="ek-table-scroll"><table><thead><tr><th>Товар / обоснование</th><th>Остаток / в пути</th><th>Прогноз / день</th><th>К заказу</th><th>Состояние</th></tr></thead><tbody>{visible.filter(r=>r.supplier===s).map(r=><tr key={r.row_id}><td><small className="ek-sku">{r.sku}</small><b>{r.name||r.sku}</b><button className="ek-reason" onClick={()=>setDetail(r.row_id)}>Обоснование <ArrowUpRight size={14}/></button><button className="ek-reason" disabled={busy} onClick={()=>openEditor(input.rows.find(item=>item.row_id===r.row_id))}>Уточнить входы</button>{r.missing_inputs.length>0&&<ul>{r.missing_inputs.map(m=><li key={m}>{m}</li>)}</ul>}</td><td><b>{show(r.free_stock)} {r.stock_unit}</b><small>+ {show(r.eligible_incoming)} учтено в пути</small></td><td><b>{show(r.daily_demand)} {r.stock_unit}</b><small>до {r.coverage_end||'—'} (не включая)</small></td><td><input className="ek-quantity" aria-label={`Заказать ${r.sku}`} disabled={busy||r.status==='needs_input'} inputMode="decimal" value={edits[r.row_id]??''} placeholder={show(r.recommended_quantity)} onChange={e=>setEdits(v=>({...v,[r.row_id]:e.target.value}))}/><small>рекомендация: {show(r.recommended_quantity)} {r.purchase_unit||'—'}</small>{edits[r.row_id]&&<input className="ek-comment" aria-label={`Причина корректировки ${r.sku}`} placeholder="Причина корректировки — обязательно" value={notes[r.row_id]||''} onChange={e=>setNotes(v=>({...v,[r.row_id]:e.target.value}))}/>}</td><td><span className={`ek-urgency ${r.status==='needs_input'?'urgent':''}`}>{r.status==='needs_input'?'Уточнить данные':'Сценарий'}</span><small>{r.basis==='synthetic'?'Синтетика':r.basis==='assumed'?'Допущения':'Наблюдения источников'}</small><small>Ранний дефицит: {show(r.maximum_prearrival_shortfall)}</small></td></tr>)}</tbody></table></div></section>)}{!visible.length&&<div className="ek-card ek-empty">Нет позиций по фильтру.</div>}</div>
          <aside className="ek-summary"><span className="ek-summary-label">{approved?'УТВЕРЖДЁН СЦЕНАРИЙ':'НА ПРОВЕРКЕ'}</span><h2>План закупки</h2><strong>{rows.length} позиций</strong><p>{scenario?`Версия ${scenario.revision}`:'Не сохранён'}</p><Field label="Название сценария" value={name} onChange={setName}/><hr/><ol><li><Calculator size={15}/>Серверный расчёт</li><li><FileText size={15}/>Проверьте количества и источники</li><li><Truck size={15}/>Утвердите конкретную версию</li></ol>{(invalid||blocked)&&<p className="ek-summary-error">{invalid||'Уточните входы всех позиций перед утверждением.'}</p>}<button className="ek-secondary" disabled={busy||!canSave} onClick={()=>run(save)}>Сохранить черновик / новую версию</button><button className="ek-primary" disabled={busy||!canApprove||approved} onClick={()=>{setAck(false);setConfirm(true);}}>Проверить и утвердить</button>{approved?<a className="ek-export" download href={`/api/v1/scenarios/${scenario.id}/export?expected_revision=${scenario.revision}`}><ArrowDownToLine size={16}/>Скачать утверждённый CSV</a>:<button className="ek-export" disabled>CSV после утверждения</button>}<small>Все {rows.length} позиций, включая скрытые фильтрами. Цены и денежная экономия не установлены. CSV содержит рекомендованные и утверждённые количества.</small></aside></div>
        </>}
      </>}
      {view==='sources'&&<section className="ek-card ek-info"><h2>Импортированные товары</h2><p>До 20 товаров. Дни без продаж не доказывают наличие товара.</p><form onSubmit={e=>{e.preventDefault();run(async()=>{const payload={...source,product_ids:Object.keys(selected)};if(!payload.normalizer_version)delete payload.normalizer_version;const prepared=await api('/planning/source-input',payload);setUsage(prepared.usage);await calculate(prepared.input);});}}><div className="ek-controls"><label>Склад<select required value={source.warehouse} onChange={e=>setSource(v=>({...v,warehouse:e.target.value}))}><option value="">Выберите склад</option>{warehouses.map(w=><option key={w.id}>{w.name}</option>)}</select></label>{[['planning_date','Дата расчёта источников'],['history_start','История с'],['history_end','История по']].map(([key,label])=><Field required key={key} label={label} type="date" value={source[key]} onChange={value=>setSource(v=>({...v,[key]:value}))}/>)}</div><div className="ek-toolbar">{[30,90,180,365].map(days=><button className="ek-secondary" type="button" key={days} onClick={()=>setSource(v=>({...v,history_start:addDays(v.history_end||today(),1-days)}))}>{days} дней истории</button>)}</div><details><summary>Исходные файлы и версия импорта</summary><Field label="Версия нормализации (при конфликте)" value={source.normalizer_version} onChange={value=>setSource(v=>({...v,normalizer_version:value}))}/>{books.map(book=><label key={book.id}><input type="checkbox" checked={source.workbook_ids.includes(book.id)} onChange={e=>setSource(v=>({...v,workbook_ids:e.target.checked?[...v.workbook_ids,book.id]:v.workbook_ids.filter(id=>id!==book.id)}))}/>{book.original_path.split(/[\\/]/).pop()}</label>)}</details><p>Выбрано {Object.keys(selected).length} из 20</p><div className="ek-toolbar">{Object.entries(selected).map(([id,item])=><button className="ek-secondary" type="button" key={id} onClick={()=>setSelected(v=>{const next={...v};delete next[id];return next;})}>Убрать {item.sku}</button>)}</div><button className="ek-primary" disabled={busy||!Object.keys(selected).length}>Подготовить и рассчитать выбранные товары</button></form>
        <form className="ek-toolbar" onSubmit={e=>{e.preventDefault();run(()=>loadCatalog());}}><Field label="Поиск кода товара" value={search} onChange={setSearch}/><button className="ek-secondary" disabled={busy}>Найти</button></form><p>{catalog.total} товаров · страница {catalog.page}</p><div className="ek-table-scroll"><table><thead><tr><th>Выбор</th><th>Товар</th><th>Поставщик</th></tr></thead><tbody>{catalog.items.map(item=><tr key={item.id}><td><input type="checkbox" aria-label={`Выбрать ${item.sku}`} disabled={busy||(!selected[item.id]&&Object.keys(selected).length>=20)} checked={!!selected[item.id]} onChange={e=>setSelected(v=>{const next={...v};if(e.target.checked)next[item.id]=item;else delete next[item.id];return next;})}/></td><td><b>{item.name}</b><small>{item.sku}{item.nameConflict?' · названия источников отличаются':''}</small></td><td>{item.supplier_name}</td></tr>)}</tbody></table></div><div className="ek-toolbar"><button className="ek-secondary" disabled={busy||catalog.page<=1} onClick={()=>run(()=>loadCatalog(catalog.page-1))}>Назад</button><button className="ek-secondary" disabled={busy||catalog.page*20>=catalog.total} onClick={()=>run(()=>loadCatalog(catalog.page+1))}>Далее</button></div>{!!usage.length&&<details><summary>Использование источников последнего расчёта</summary>{usage.map((u,i)=><p key={i}><b>{u.source} · {u.status}</b><br/>{u.reason}</p>)}</details>}
      </section>}
      {view==='method'&&<section className="ek-card ek-info"><h2>Почему предложено именно столько</h2><ol className="ek-method"><li><b>История и разовые заказы</b><p>Сервер использует календарную среднюю либо явный дневной спрос. Статистическая политика выделяет кандидатов крупных заказов, сохраняя повторяющееся повышение спроса. Это не доказательство намерения клиента.</p></li><li><b>Дефицит и сезонность</b><p>Потерянный спрос оценивается по переданным дням отсутствия и сопоставимым дням недели. Месячные факторы, рост и буферы — явные настройки, а не автоматически выбранная исследовательская модель.</p></li><li><b>Заказ и сроки</b><p>Горизонт = срок новой поставки + интервал пересмотра. Из спроса с буфером вычитаются свободный остаток и подходящие поступления. Затем — перевод закупочных единиц, MOQ и кратность. Дневной баланс отдельно показывает ранний дефицит.</p></li><li><b>Утверждение</b><p>Корректировки требуют причины. Сервер сохраняет версии; изменение снимает утверждение. CSV содержит оба количества и источники. BOM и совместимость с конкретной конфигурацией 1С пока не подтверждены.</p></li></ol></section>}
      <footer className="ek-footer">Электрокомплект · HackAlem AI<span>Сохранённые сценарии остаются после перезагрузки</span></footer>
    </main>
    <dialog ref={dialog} className="ek-dialog" onCancel={close} onClose={close}><header><h2>{confirm?'Утвердить сценарий?':editor?`Уточнить ${editor.sku}`:resultRow?.name||resultRow?.sku}</h2><button aria-label="Закрыть" disabled={busy} onClick={close}><X/></button></header>{error&&<p role="alert" className="ek-warning">{error}</p>}
      {confirm?<><p>Все {rows.length} позиций, включая скрытые фильтром. {changed?'Перед утверждением будет сохранена новая версия.':`Версия ${scenario.revision}.`}</p><ul>{rows.map(r=><li key={r.row_id}>{r.supplier} / {r.sku}: {edits[r.row_id]||show(r.recommended_quantity)} {r.purchase_unit}</li>)}</ul><Field label="Ответственный сотрудник" value={actor} onChange={setActor}/><label><input type="checkbox" checked={ack} onChange={e=>setAck(e.target.checked)}/>Я проверил количества и принимаю сценарные допущения</label><p>Это утверждение сценария, а не отправка поставщику.</p><button className="ek-primary" disabled={busy||!canApprove||!actor.trim()||!ack} onClick={()=>run(approve)}>Утвердить сценарий</button></>:editor?<form onSubmit={e=>{e.preventDefault();if(!reason.trim()){setError('Укажите причину уточнения.');return;}run(async()=>{await calculate({...input,rows:input.rows.map(r=>r.row_id===editor.row_id?{...editor,basis:'assumed',notes:[...editor.notes,reason.trim()]}:r)});setEditor(null);});}}><p>Проверенные значения или явные допущения. Исходники не изменяются.</p><div className="ek-edit-inputs">
        {[['warehouse','Склад позиции'],['stock_unit','Единица хранения'],['purchase_unit','Единица закупки'],['free_stock','Свободный остаток'],['stock_per_purchase_unit','Единиц хранения в закупочной единице'],['minimum_order','MOQ'],['order_multiple','Кратность'],['daily_demand','Явный спрос в день (пусто — история)'],['buffer_days','Буфер позиции, дней (пусто — общий)'],['growth_pct','Рост позиции, % (пусто — общий)']].map(([key,label])=><Field key={key} label={label} value={editor[key]} onChange={value=>setEditor(v=>({...v,[key]:nullable(value)}))}/>)}<Field label="Остаток на дату" type="date" value={editor.stock_as_of} onChange={value=>setEditor(v=>({...v,stock_as_of:nullable(value)}))}/><Field label="Срок поставки позиции, дней" type="number" min="0" max="365" value={editor.lead_time_days} onChange={value=>setEditor(v=>({...v,lead_time_days:value===''?null:Number(value)}))}/></div><p>История: {editor.history_start||'не установлена'} — {editor.history_end||'не установлена'}. Документов: {editor.sales.length}.</p>
        {[['stock_scope_confirmed','Склад остатка проверен для сценария'],['incoming_complete','Список поступлений полон для сценария'],['constraints_confirmed','Единицы и закупочные условия проверены для сценария']].map(([key,label])=><label key={key}><input type="checkbox" checked={editor[key]} onChange={e=>setEditor(v=>({...v,[key]:e.target.checked}))}/>{label}</label>)}
        <h3>Поступления</h3>{editor.incoming.map((incoming,index)=><fieldset key={incoming.id}><legend>Поступление {index+1}</legend><div className="ek-edit-inputs">{[['quantity','Количество','text'],['expected_on','Дата прихода','date'],['warehouse','Склад поступления','text'],['stock_unit','Единица поступления','text']].map(([key,label,type])=><Field key={key} label={`${label} ${index+1}`} type={type} value={incoming[key]} onChange={value=>setEditor(v=>({...v,incoming:v.incoming.map((item,i)=>i===index?{...item,[key]:nullable(value)}:item)}))}/>)}</div></fieldset>)}<Field required label="Причина уточнения / источник проверки" value={reason} onChange={setReason}/><button className="ek-primary" disabled={busy}>Применить входы и пересчитать</button>
      </form>:resultRow&&<><p>{resultRow.supplier} · {resultRow.sku} · {sourceRow?.warehouse}</p><div className="ek-formula">{resultRow.explanation}</div><dl className="ek-evidence">{[['Спрос за горизонт',resultRow.forecast_demand],['Буфер',resultRow.buffer],['Остаток',resultRow.free_stock],['Подходящие поступления',resultRow.eligible_incoming],['Чистая потребность',resultRow.raw_need],['Рекомендовано',resultRow.recommended_quantity],['Избыток округления',resultRow.rounding_surplus],['Исключённые всплески',resultRow.excluded_bulk_quantity],['Потерянный спрос',resultRow.lost_demand_quantity],['Приход нового заказа',resultRow.arrival_date],['Конец покрытия (не включая)',resultRow.coverage_end],['Дефицит до прихода',resultRow.maximum_prearrival_shortfall]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{show(value)}</dd></div>)}</dl><ul>{[...resultRow.missing_inputs,...resultRow.warnings,...resultRow.demand_adjustments,...(sourceRow?.notes||[])].map((m,i)=><li key={i}>{m}</li>)}</ul><details><summary>Дневной баланс</summary><table><thead><tr><th>Дата</th><th>Спрос</th><th>Приход</th><th>Баланс</th></tr></thead><tbody>{resultRow.daily_balances.map(day=><tr key={day.day}><td>{day.day}</td><td>{day.demand}</td><td>{day.incoming}</td><td>{day.balance}</td></tr>)}</tbody></table></details><details><summary>Источники</summary>{resultRow.sources.map((s,i)=><p key={i}>{s.label}</p>)}</details><button className="ek-primary" disabled={busy} onClick={()=>openEditor(sourceRow)}>Уточнить входы</button></>}
    </dialog>
  </div>;
}
