import {useEffect,useState} from 'react';
import {api} from './api.js';

export default function SavedOrders({refresh=0}){
  const [items,setItems]=useState([]),[selected,setSelected]=useState(null),[query,setQuery]=useState(''),[error,setError]=useState('');
  useEffect(()=>{api('/scenarios').then(data=>setItems(data.items)).catch(e=>setError(e.message));},[refresh]);
  async function open(id){try{setError('');setSelected(await api(`/scenarios/${id}`));}catch(e){setError(e.message);}}
  return <section className="ek-card ek-info ek-order-history"><h2>История заказов</h2><p>Сохранённые количества, обоснования и ответственный остаются доступны после перезагрузки.</p><label>Найти заказ<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Название или номер"/></label>{error&&<p role="alert">{error}</p>}
    <div className="ek-history-list">{items.filter(item=>`${item.name} ${item.id}`.toLocaleLowerCase('ru').includes(query.toLocaleLowerCase('ru'))).map(item=><button className="ek-secondary" key={item.id} onClick={()=>open(item.id)}>{item.name} · v{item.revision} · {item.approved_revision===item.revision?'Утверждён':'Черновик'}</button>)}{!items.length&&<p>Сохранённых заказов пока нет.</p>}</div>
    {selected&&<><h3>{selected.name}</h3><p>№ {selected.id} · версия {selected.revision}<br/>{selected.approved_by?`Утвердил: ${selected.approved_by} · ${new Date(selected.approved_at).toLocaleString('ru-RU')}`:'Не утверждён'}</p><div className="ek-table-scroll"><table><thead><tr><th>Поставщик / товар</th><th>Рекомендовано</th><th>Согласовано</th><th>Причина</th></tr></thead><tbody>{selected.result.rows.map(row=>{const override=selected.overrides.find(o=>o.row_id===row.row_id);return <tr key={row.row_id}><td>{row.supplier}<b>{row.sku} · {row.name}</b></td><td>{row.recommended_quantity} {row.purchase_unit}</td><td>{override?.quantity??row.recommended_quantity} {row.purchase_unit}</td><td>{override?.reason||row.explanation}</td></tr>;})}</tbody></table></div>{selected.approved_revision===selected.revision&&<a className="ek-secondary" download href={`/api/v1/scenarios/${selected.id}/export?expected_revision=${selected.revision}`}>Скачать утверждённый CSV</a>}</>}
  </section>;
}

export function SourceDetails({row,onApply}){
  const [draft,setDraft]=useState(row.source),[reason,setReason]=useState('');
  const fields=[['free_stock','Свободный остаток'],['stock_as_of','Остаток на дату','date'],['purchase_unit','Единица закупки'],['stock_per_purchase_unit','Единиц хранения в закупочной единице'],['minimum_order','Минимальный заказ'],['order_multiple','Кратность заказа'],['lead_time_days','Срок поставки, дней','number'],['daily_demand','Спрос в день (пусто — по истории)']];
  return <><div className="ek-formula">{row.reason}</div><dl className="ek-evidence">{[['Прогноз за период',row.target],['Свободный остаток',row.stock],['Учтено в пути',row.incoming],['Чистая потребность',row.net],['Рекомендовано',row.quantityExact]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value??'Не установлено'}</dd></div>)}</dl>
    {!!row.api.missing_inputs?.length&&<div className="ek-warning"><b>Требуют уточнения</b><ul>{row.api.missing_inputs.map(value=><li key={value}>{value}</li>)}</ul></div>}
    <details><summary>История, расчёт и источники</summary><p>{row.source.sales.length} строк продаж · {row.source.history_start} — {row.source.history_end}</p><div className="ek-table-scroll"><table><thead><tr><th>Дата</th><th>Прогноз</th><th>Приход</th><th>Остаток</th></tr></thead><tbody>{row.api.daily_balances.map(day=><tr key={day.day}><td>{day.day}</td><td>{day.demand}</td><td>{day.incoming}</td><td>{day.balance}</td></tr>)}</tbody></table></div>{row.api.sources.map((s,i)=><p key={i}>{s.label}</p>)}</details>
    <details><summary>Уточнить исходные данные</summary><form onSubmit={e=>{e.preventDefault();onApply({...draft,basis:'assumed',notes:[...draft.notes,reason.trim()]});}}><div className="ek-edit-inputs">{fields.map(([key,label,type='text'])=><label key={key}>{label}<input type={type} value={draft[key]??''} onChange={e=>setDraft(v=>({...v,[key]:e.target.value===''?null:key==='lead_time_days'?Number(e.target.value):e.target.value}))}/></label>)}</div>{[['stock_scope_confirmed','Склад остатка проверен'],['incoming_complete','Все поступления учтены'],['constraints_confirmed','Условия закупки проверены']].map(([key,label])=><label key={key}><input type="checkbox" checked={draft[key]} onChange={e=>setDraft(v=>({...v,[key]:e.target.checked}))}/>{label}</label>)}<label>Причина уточнения<input required value={reason} onChange={e=>setReason(e.target.value)}/></label><button className="ek-primary" disabled={!reason.trim()}>Применить и пересчитать</button></form></details>
  </>;
}
