"""excel_data_foundation

Revision: 0001
Revises:
"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "catalog_suppliers",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_catalog_suppliers")),
        sa.UniqueConstraint("code", name=op.f("uq_catalog_suppliers_code")),
    )
    op.create_table(
        "catalog_warehouses",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_catalog_warehouses")),
        sa.UniqueConstraint("name", name=op.f("uq_catalog_warehouses_name")),
    )
    op.create_table(
        "intake_workbooks",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("sha256", sa.String(), nullable=False),
        sa.Column("original_path", sa.String(), nullable=False),
        sa.Column("archive_name", sa.String(), nullable=True),
        sa.Column("byte_size", sa.Integer(), nullable=False),
        sa.Column("content", sa.LargeBinary(), nullable=False),
        sa.Column("captured_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("capture_version", sa.String(), nullable=False),
        sa.CheckConstraint(
            "sha256 = encode(sha256(content), 'hex')", name=op.f("ck_intake_workbooks_content_hash")
        ),
        sa.CheckConstraint("sha256 ~ '^[0-9a-f]{64}$'", name=op.f("ck_intake_workbooks_sha256_format")),
        sa.CheckConstraint(
            "byte_size = octet_length(content)", name=op.f("ck_intake_workbooks_content_size")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_intake_workbooks")),
        sa.UniqueConstraint("sha256", name=op.f("uq_intake_workbooks_sha256")),
    )
    op.create_table(
        "catalog_products",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("supplier_id", sa.Uuid(), nullable=False),
        sa.Column("sku", sa.String(), nullable=False),
        sa.CheckConstraint("length(sku) > 0", name=op.f("ck_catalog_products_nonempty_sku")),
        sa.ForeignKeyConstraint(
            ["supplier_id"],
            ["catalog_suppliers.id"],
            name=op.f("fk_catalog_products_supplier_id_catalog_suppliers"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_catalog_products")),
        sa.UniqueConstraint("id", "supplier_id", name=op.f("uq_catalog_products_id")),
        sa.UniqueConstraint("supplier_id", "sku", name=op.f("uq_catalog_products_supplier_id")),
    )
    op.create_table(
        "intake_findings",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workbook_id", sa.Uuid(), nullable=False),
        sa.Column("finding_key", sa.String(), nullable=False),
        sa.Column("code", sa.String(), nullable=False),
        sa.Column("evidence", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("resolution", sa.String(), nullable=True),
        sa.CheckConstraint(
            "status IN ('open', 'resolved', 'accepted_limitation')", name=op.f("ck_intake_findings_status")
        ),
        sa.ForeignKeyConstraint(
            ["workbook_id"],
            ["intake_workbooks.id"],
            name=op.f("fk_intake_findings_workbook_id_intake_workbooks"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_intake_findings")),
        sa.UniqueConstraint("workbook_id", "finding_key", name=op.f("uq_intake_findings_workbook_id")),
    )
    op.create_table(
        "intake_sheets",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workbook_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("reported_rows", sa.Integer(), nullable=False),
        sa.Column("reported_columns", sa.Integer(), nullable=False),
        sa.Column("layout", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.CheckConstraint(
            "position >= 0 AND reported_rows >= 0 AND reported_columns >= 0",
            name=op.f("ck_intake_sheets_dimensions"),
        ),
        sa.ForeignKeyConstraint(
            ["workbook_id"],
            ["intake_workbooks.id"],
            name=op.f("fk_intake_sheets_workbook_id_intake_workbooks"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_intake_sheets")),
        sa.UniqueConstraint("workbook_id", "name", name=op.f("uq_intake_sheets_workbook_id")),
    )
    op.create_table(
        "intake_rows",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("sheet_id", sa.Uuid(), nullable=False),
        sa.Column("row_number", sa.Integer(), nullable=False),
        sa.Column("cells", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.CheckConstraint("jsonb_typeof(cells) = 'object'", name=op.f("ck_intake_rows_cells_object")),
        sa.CheckConstraint("row_number > 0", name=op.f("ck_intake_rows_positive_row")),
        sa.ForeignKeyConstraint(
            ["sheet_id"], ["intake_sheets.id"], name=op.f("fk_intake_rows_sheet_id_intake_sheets")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_intake_rows")),
        sa.UniqueConstraint("sheet_id", "row_number", name=op.f("uq_intake_rows_sheet_id")),
    )
    op.create_table(
        "supply_shipments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("supplier_id", sa.Uuid(), nullable=False),
        sa.Column("source_sheet_id", sa.Uuid(), nullable=False),
        sa.Column("source_column", sa.String(), nullable=False),
        sa.Column("normalizer_version", sa.String(), nullable=False),
        sa.Column("header", sa.String(), nullable=False),
        sa.Column("document_number", sa.String(), nullable=True),
        sa.Column("ordered_on", sa.Date(), nullable=True),
        sa.Column("expected_on", sa.Date(), nullable=True),
        sa.Column("date_basis", sa.String(), nullable=False),
        sa.Column("warehouse_id", sa.Uuid(), nullable=True),
        sa.CheckConstraint(
            "date_basis IN ('explicit', 'assumed_year', 'unknown')",
            name=op.f("ck_supply_shipments_date_basis"),
        ),
        sa.ForeignKeyConstraint(
            ["source_sheet_id"],
            ["intake_sheets.id"],
            name=op.f("fk_supply_shipments_source_sheet_id_intake_sheets"),
        ),
        sa.ForeignKeyConstraint(
            ["supplier_id"],
            ["catalog_suppliers.id"],
            name=op.f("fk_supply_shipments_supplier_id_catalog_suppliers"),
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["catalog_warehouses.id"],
            name=op.f("fk_supply_shipments_warehouse_id_catalog_warehouses"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_supply_shipments")),
        sa.UniqueConstraint("id", "supplier_id", name=op.f("uq_supply_shipments_id")),
        sa.UniqueConstraint(
            "source_sheet_id",
            "source_column",
            "normalizer_version",
            name=op.f("uq_supply_shipments_source_sheet_id"),
        ),
    )
    op.create_table(
        "catalog_product_observations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("source_row_id", sa.Uuid(), nullable=False),
        sa.Column("normalizer_version", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("supplier_article", sa.String(), nullable=True),
        sa.Column("unit", sa.String(), nullable=True),
        sa.Column("category_code", sa.String(), nullable=True),
        sa.Column("category_year", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["catalog_products.id"],
            name=op.f("fk_catalog_product_observations_product_id_catalog_products"),
        ),
        sa.ForeignKeyConstraint(
            ["source_row_id"],
            ["intake_rows.id"],
            name=op.f("fk_catalog_product_observations_source_row_id_intake_rows"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_catalog_product_observations")),
        sa.UniqueConstraint(
            "source_row_id", "normalizer_version", name=op.f("uq_catalog_product_observations_source_row_id")
        ),
    )
    op.create_index(
        op.f("ix_catalog_product_observations_product_id"),
        "catalog_product_observations",
        ["product_id"],
        unique=False,
    )
    op.create_table(
        "demand_monthly_sales",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source_row_id", sa.Uuid(), nullable=False),
        sa.Column("source_column", sa.String(), nullable=False),
        sa.Column("normalizer_version", sa.String(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("warehouse_id", sa.Uuid(), nullable=True),
        sa.Column("month", sa.Date(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=30, scale=12), nullable=True),
        sa.Column("unit", sa.String(), nullable=True),
        sa.Column("is_complete_period", sa.Boolean(), nullable=True),
        sa.CheckConstraint("extract(day FROM month) = 1", name=op.f("ck_demand_monthly_sales_month_start")),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["catalog_products.id"],
            name=op.f("fk_demand_monthly_sales_product_id_catalog_products"),
        ),
        sa.ForeignKeyConstraint(
            ["source_row_id"],
            ["intake_rows.id"],
            name=op.f("fk_demand_monthly_sales_source_row_id_intake_rows"),
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["catalog_warehouses.id"],
            name=op.f("fk_demand_monthly_sales_warehouse_id_catalog_warehouses"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_demand_monthly_sales")),
        sa.UniqueConstraint(
            "source_row_id",
            "source_column",
            "normalizer_version",
            name=op.f("uq_demand_monthly_sales_source_row_id"),
        ),
    )
    op.create_index(op.f("ix_demand_monthly_sales_month"), "demand_monthly_sales", ["month"], unique=False)
    op.create_index(
        op.f("ix_demand_monthly_sales_product_id"), "demand_monthly_sales", ["product_id"], unique=False
    )
    op.create_table(
        "demand_movements",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source_row_id", sa.Uuid(), nullable=False),
        sa.Column("normalizer_version", sa.String(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("warehouse_id", sa.Uuid(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(), nullable=False),
        sa.Column("document_number", sa.String(), nullable=False),
        sa.Column("document_text", sa.String(), nullable=False),
        sa.Column("unit", sa.String(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=30, scale=12), nullable=True),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["catalog_products.id"],
            name=op.f("fk_demand_movements_product_id_catalog_products"),
        ),
        sa.ForeignKeyConstraint(
            ["source_row_id"], ["intake_rows.id"], name=op.f("fk_demand_movements_source_row_id_intake_rows")
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["catalog_warehouses.id"],
            name=op.f("fk_demand_movements_warehouse_id_catalog_warehouses"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_demand_movements")),
        sa.UniqueConstraint(
            "source_row_id", "normalizer_version", name=op.f("uq_demand_movements_source_row_id")
        ),
    )
    op.create_index(
        op.f("ix_demand_movements_occurred_at"), "demand_movements", ["occurred_at"], unique=False
    )
    op.create_index(op.f("ix_demand_movements_product_id"), "demand_movements", ["product_id"], unique=False)
    op.create_table(
        "demand_report_metrics",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source_row_id", sa.Uuid(), nullable=False),
        sa.Column("source_column", sa.String(), nullable=False),
        sa.Column("normalizer_version", sa.String(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("metric", sa.String(), nullable=False),
        sa.Column("label", sa.String(), nullable=False),
        sa.Column("value", sa.Numeric(precision=30, scale=12), nullable=True),
        sa.Column("unit", sa.String(), nullable=True),
        sa.Column("period_start", sa.Date(), nullable=True),
        sa.Column("period_end", sa.Date(), nullable=True),
        sa.CheckConstraint(
            "metric IN ('sales_total', 'sales_average', 'growth_change', 'seasonality_change', "
            "'cost_unspecified', 'coverage_unspecified', 'planned_order', "
            "'weight_unspecified', 'stock_total')",
            name=op.f("ck_demand_report_metrics_metric"),
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["catalog_products.id"],
            name=op.f("fk_demand_report_metrics_product_id_catalog_products"),
        ),
        sa.ForeignKeyConstraint(
            ["source_row_id"],
            ["intake_rows.id"],
            name=op.f("fk_demand_report_metrics_source_row_id_intake_rows"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_demand_report_metrics")),
        sa.UniqueConstraint(
            "source_row_id",
            "source_column",
            "normalizer_version",
            name=op.f("uq_demand_report_metrics_source_row_id"),
        ),
    )
    op.create_index(
        op.f("ix_demand_report_metrics_product_id"), "demand_report_metrics", ["product_id"], unique=False
    )
    op.create_table(
        "demand_seasonality_observations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source_row_id", sa.Uuid(), nullable=False),
        sa.Column("source_column", sa.String(), nullable=False),
        sa.Column("normalizer_version", sa.String(), nullable=False),
        sa.Column("supplier_id", sa.Uuid(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.Column("month", sa.Integer(), nullable=True),
        sa.Column("metric", sa.String(), nullable=False),
        sa.Column("label", sa.String(), nullable=False),
        sa.Column("value", sa.Numeric(precision=30, scale=12), nullable=True),
        sa.Column("unit", sa.String(), nullable=True),
        sa.Column("basis", sa.String(), nullable=False),
        sa.CheckConstraint(
            "basis IN ('reported', 'derived', 'forecast', 'unknown')",
            name=op.f("ck_demand_seasonality_observations_basis"),
        ),
        sa.CheckConstraint(
            "month IS NULL OR month BETWEEN 1 AND 12", name=op.f("ck_demand_seasonality_observations_month")
        ),
        sa.ForeignKeyConstraint(
            ["source_row_id"],
            ["intake_rows.id"],
            name=op.f("fk_demand_seasonality_observations_source_row_id_intake_rows"),
        ),
        sa.ForeignKeyConstraint(
            ["supplier_id"],
            ["catalog_suppliers.id"],
            name=op.f("fk_demand_seasonality_observations_supplier_id_catalog_suppliers"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_demand_seasonality_observations")),
        sa.UniqueConstraint(
            "source_row_id",
            "source_column",
            "normalizer_version",
            name=op.f("uq_demand_seasonality_observations_source_row_id"),
        ),
    )
    op.create_table(
        "inventory_monthly_stock",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source_row_id", sa.Uuid(), nullable=False),
        sa.Column("source_column", sa.String(), nullable=False),
        sa.Column("normalizer_version", sa.String(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("warehouse_id", sa.Uuid(), nullable=True),
        sa.Column("month", sa.Date(), nullable=False),
        sa.Column("metric", sa.String(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=30, scale=12), nullable=True),
        sa.Column("unit", sa.String(), nullable=True),
        sa.CheckConstraint(
            "metric IN ('opening_stock', 'stock_unspecified')", name=op.f("ck_inventory_monthly_stock_metric")
        ),
        sa.CheckConstraint(
            "extract(day FROM month) = 1", name=op.f("ck_inventory_monthly_stock_month_start")
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["catalog_products.id"],
            name=op.f("fk_inventory_monthly_stock_product_id_catalog_products"),
        ),
        sa.ForeignKeyConstraint(
            ["source_row_id"],
            ["intake_rows.id"],
            name=op.f("fk_inventory_monthly_stock_source_row_id_intake_rows"),
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["catalog_warehouses.id"],
            name=op.f("fk_inventory_monthly_stock_warehouse_id_catalog_warehouses"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_inventory_monthly_stock")),
        sa.UniqueConstraint(
            "source_row_id",
            "source_column",
            "normalizer_version",
            name=op.f("uq_inventory_monthly_stock_source_row_id"),
        ),
    )
    op.create_index(
        op.f("ix_inventory_monthly_stock_month"), "inventory_monthly_stock", ["month"], unique=False
    )
    op.create_index(
        op.f("ix_inventory_monthly_stock_product_id"), "inventory_monthly_stock", ["product_id"], unique=False
    )
    op.create_table(
        "inventory_observations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source_row_id", sa.Uuid(), nullable=False),
        sa.Column("source_column", sa.String(), nullable=False),
        sa.Column("normalizer_version", sa.String(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("warehouse_id", sa.Uuid(), nullable=True),
        sa.Column("scope_label", sa.String(), nullable=False),
        sa.Column("as_of", sa.Date(), nullable=True),
        sa.Column("date_basis", sa.String(), nullable=False),
        sa.Column("metric", sa.String(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=30, scale=12), nullable=True),
        sa.Column("unit", sa.String(), nullable=True),
        sa.CheckConstraint(
            "date_basis IN ('explicit', 'filename', 'assumed', 'unknown')",
            name=op.f("ck_inventory_observations_date_basis"),
        ),
        sa.CheckConstraint(
            "metric IN ('on_hand', 'reserved', 'free', 'showroom', 'trading_area', "
            "'distribution_center', 'retail')",
            name=op.f("ck_inventory_observations_metric"),
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["catalog_products.id"],
            name=op.f("fk_inventory_observations_product_id_catalog_products"),
        ),
        sa.ForeignKeyConstraint(
            ["source_row_id"],
            ["intake_rows.id"],
            name=op.f("fk_inventory_observations_source_row_id_intake_rows"),
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["catalog_warehouses.id"],
            name=op.f("fk_inventory_observations_warehouse_id_catalog_warehouses"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_inventory_observations")),
        sa.UniqueConstraint(
            "source_row_id",
            "source_column",
            "normalizer_version",
            name=op.f("uq_inventory_observations_source_row_id"),
        ),
    )
    op.create_index(
        op.f("ix_inventory_observations_product_id"), "inventory_observations", ["product_id"], unique=False
    )
    op.create_table(
        "supply_quantity_rules",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source_row_id", sa.Uuid(), nullable=False),
        sa.Column("source_column", sa.String(), nullable=False),
        sa.Column("normalizer_version", sa.String(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("label", sa.String(), nullable=False),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("value", sa.Numeric(precision=30, scale=12), nullable=True),
        sa.Column("unit", sa.String(), nullable=True),
        sa.Column("interpretation_confirmed", sa.Boolean(), nullable=False),
        sa.CheckConstraint(
            "kind IN ('minimum_shipment', 'order_multiple', 'unconfirmed')",
            name=op.f("ck_supply_quantity_rules_kind"),
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["catalog_products.id"],
            name=op.f("fk_supply_quantity_rules_product_id_catalog_products"),
        ),
        sa.ForeignKeyConstraint(
            ["source_row_id"],
            ["intake_rows.id"],
            name=op.f("fk_supply_quantity_rules_source_row_id_intake_rows"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_supply_quantity_rules")),
        sa.UniqueConstraint(
            "source_row_id",
            "source_column",
            "normalizer_version",
            name=op.f("uq_supply_quantity_rules_source_row_id"),
        ),
    )
    op.create_index(
        op.f("ix_supply_quantity_rules_product_id"), "supply_quantity_rules", ["product_id"], unique=False
    )
    op.create_table(
        "supply_shipment_lines",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("shipment_id", sa.Uuid(), nullable=False),
        sa.Column("supplier_id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("source_row_id", sa.Uuid(), nullable=False),
        sa.Column("source_column", sa.String(), nullable=False),
        sa.Column("normalizer_version", sa.String(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=30, scale=12), nullable=True),
        sa.Column("unit", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["product_id", "supplier_id"],
            ["catalog_products.id", "catalog_products.supplier_id"],
            name=op.f("fk_supply_shipment_lines_product_id_catalog_products"),
        ),
        sa.ForeignKeyConstraint(
            ["shipment_id", "supplier_id"],
            ["supply_shipments.id", "supply_shipments.supplier_id"],
            name=op.f("fk_supply_shipment_lines_shipment_id_supply_shipments"),
        ),
        sa.ForeignKeyConstraint(
            ["source_row_id"],
            ["intake_rows.id"],
            name=op.f("fk_supply_shipment_lines_source_row_id_intake_rows"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_supply_shipment_lines")),
        sa.UniqueConstraint(
            "source_row_id",
            "source_column",
            "normalizer_version",
            name=op.f("uq_supply_shipment_lines_source_row_id"),
        ),
    )
    op.create_index(
        op.f("ix_supply_shipment_lines_product_id"), "supply_shipment_lines", ["product_id"], unique=False
    )
    op.create_index(
        op.f("ix_supply_shipment_lines_shipment_id"), "supply_shipment_lines", ["shipment_id"], unique=False
    )
    # Source evidence is append-only. A replacement workbook has a new content hash.
    op.execute("""
        CREATE FUNCTION reject_evidence_change() RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
            RAISE EXCEPTION 'Source evidence is immutable; insert a new source version';
        END;
        $$
    """)
    for table in ("intake_workbooks", "intake_sheets", "intake_rows"):
        op.execute(
            f"CREATE TRIGGER immutable_evidence BEFORE UPDATE OR DELETE ON {table} "
            "FOR EACH ROW EXECUTE FUNCTION reject_evidence_change()"
        )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_supply_shipment_lines_shipment_id"), table_name="supply_shipment_lines")
    op.drop_index(op.f("ix_supply_shipment_lines_product_id"), table_name="supply_shipment_lines")
    op.drop_table("supply_shipment_lines")
    op.drop_index(op.f("ix_supply_quantity_rules_product_id"), table_name="supply_quantity_rules")
    op.drop_table("supply_quantity_rules")
    op.drop_index(op.f("ix_inventory_observations_product_id"), table_name="inventory_observations")
    op.drop_table("inventory_observations")
    op.drop_index(op.f("ix_inventory_monthly_stock_product_id"), table_name="inventory_monthly_stock")
    op.drop_index(op.f("ix_inventory_monthly_stock_month"), table_name="inventory_monthly_stock")
    op.drop_table("inventory_monthly_stock")
    op.drop_table("demand_seasonality_observations")
    op.drop_index(op.f("ix_demand_report_metrics_product_id"), table_name="demand_report_metrics")
    op.drop_table("demand_report_metrics")
    op.drop_index(op.f("ix_demand_movements_product_id"), table_name="demand_movements")
    op.drop_index(op.f("ix_demand_movements_occurred_at"), table_name="demand_movements")
    op.drop_table("demand_movements")
    op.drop_index(op.f("ix_demand_monthly_sales_product_id"), table_name="demand_monthly_sales")
    op.drop_index(op.f("ix_demand_monthly_sales_month"), table_name="demand_monthly_sales")
    op.drop_table("demand_monthly_sales")
    op.drop_index(
        op.f("ix_catalog_product_observations_product_id"), table_name="catalog_product_observations"
    )
    op.drop_table("catalog_product_observations")
    op.drop_table("supply_shipments")
    op.drop_table("intake_rows")
    op.drop_table("intake_sheets")
    op.drop_table("intake_findings")
    op.drop_table("catalog_products")
    op.drop_table("intake_workbooks")
    op.drop_table("catalog_warehouses")
    op.drop_table("catalog_suppliers")
    op.execute("DROP FUNCTION reject_evidence_change()")
    # ### end Alembic commands ###
