"""forecast_first_calculation

Revision: 0002
Revises: 0001
"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "0002"
down_revision = "0001"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "calculation_runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("fingerprint", sa.String(), nullable=False),
        sa.Column("contract_version", sa.String(), nullable=False),
        sa.Column("planning_date", sa.Date(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("source_selection", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("parameters", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("versions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("quality", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("llm_accounting", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("failure", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.CheckConstraint("fingerprint ~ '^[0-9a-f]{64}$'", name=op.f("ck_calculation_runs_fingerprint")),
        sa.CheckConstraint(
            "status IN ('running', 'completed', 'failed')", name=op.f("ck_calculation_runs_status")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_calculation_runs")),
    )
    op.create_index(
        op.f("ix_calculation_runs_fingerprint"), "calculation_runs", ["fingerprint"], unique=False
    )
    op.create_table(
        "calculation_inputs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("series_id", sa.String(), nullable=False),
        sa.Column("supplier", sa.String(), nullable=False),
        sa.Column("sku", sa.String(), nullable=False),
        sa.Column("scope", sa.String(), nullable=False),
        sa.Column("unit", sa.String(), nullable=True),
        sa.Column("snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"], ["calculation_runs.id"], name=op.f("fk_calculation_inputs_run_id_calculation_runs")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_calculation_inputs")),
        sa.UniqueConstraint("run_id", "series_id", name=op.f("uq_calculation_inputs_run_id")),
    )
    op.create_index(op.f("ix_calculation_inputs_run_id"), "calculation_inputs", ["run_id"], unique=False)
    op.create_table(
        "calculation_drafts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("series_id", sa.String(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=30, scale=12), nullable=True),
        sa.Column("purchase_unit", sa.String(), nullable=True),
        sa.Column("coverage_start", sa.Date(), nullable=False),
        sa.Column("coverage_end", sa.Date(), nullable=False),
        sa.Column("urgency", sa.String(), nullable=False),
        sa.Column("state", sa.String(), nullable=False),
        sa.Column("blocking_reason", sa.String(), nullable=True),
        sa.Column("components", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("evidence", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("assumptions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.CheckConstraint(
            "(state = 'blocked') = (quantity IS NULL)", name=op.f("ck_calculation_drafts_quantity_state")
        ),
        sa.CheckConstraint(
            "quantity >= 0 AND quantity <> 'NaN'::numeric", name=op.f("ck_calculation_drafts_nonnegative")
        ),
        sa.CheckConstraint(
            "state IN ('ready', 'estimated', 'blocked')", name=op.f("ck_calculation_drafts_state")
        ),
        sa.CheckConstraint("coverage_end >= coverage_start", name=op.f("ck_calculation_drafts_coverage")),
        sa.ForeignKeyConstraint(
            ["run_id", "series_id"],
            ["calculation_inputs.run_id", "calculation_inputs.series_id"],
            name=op.f("fk_calculation_drafts_run_id_calculation_inputs"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_calculation_drafts")),
        sa.UniqueConstraint("run_id", "series_id", name=op.f("uq_calculation_drafts_run_id")),
    )
    op.create_index(op.f("ix_calculation_drafts_run_id"), "calculation_drafts", ["run_id"], unique=False)
    op.create_table(
        "calculation_forecasts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("series_id", sa.String(), nullable=False),
        sa.Column("target_month", sa.Date(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=30, scale=12), nullable=True),
        sa.Column("model", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("explanation", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.CheckConstraint(
            "(status = 'ok') = (quantity IS NOT NULL)", name=op.f("ck_calculation_forecasts_quantity_status")
        ),
        sa.CheckConstraint(
            "quantity >= 0 AND quantity <> 'NaN'::numeric", name=op.f("ck_calculation_forecasts_nonnegative")
        ),
        sa.CheckConstraint(
            "status IN ('ok', 'insufficient_data', 'unsupported')",
            name=op.f("ck_calculation_forecasts_status"),
        ),
        sa.CheckConstraint(
            "extract(day from target_month) = 1", name=op.f("ck_calculation_forecasts_month_start")
        ),
        sa.ForeignKeyConstraint(
            ["run_id", "series_id"],
            ["calculation_inputs.run_id", "calculation_inputs.series_id"],
            name=op.f("fk_calculation_forecasts_run_id_calculation_inputs"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_calculation_forecasts")),
        sa.UniqueConstraint(
            "run_id", "series_id", "target_month", name=op.f("uq_calculation_forecasts_run_id")
        ),
    )
    op.create_index(
        op.f("ix_calculation_forecasts_run_id"), "calculation_forecasts", ["run_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_calculation_forecasts_run_id"), table_name="calculation_forecasts")
    op.drop_table("calculation_forecasts")
    op.drop_index(op.f("ix_calculation_drafts_run_id"), table_name="calculation_drafts")
    op.drop_table("calculation_drafts")
    op.drop_index(op.f("ix_calculation_inputs_run_id"), table_name="calculation_inputs")
    op.drop_table("calculation_inputs")
    op.drop_index(op.f("ix_calculation_runs_fingerprint"), table_name="calculation_runs")
    op.drop_table("calculation_runs")
    # ### end Alembic commands ###
